from hearthstone.enums import CardSet

set_names = {
    CardSet.BASIC: "Basic",
    CardSet.EXPERT1: "Classic",
    CardSet.HOF: "Hall of Fame",
    CardSet.MISSIONS: "Missions",
    CardSet.NONE: "System",
    CardSet.CHEAT: "Debug",
    CardSet.PROMO: "Promotion",
    CardSet.NAXX: "Curse of Naxxramas",
    CardSet.GVG: "Goblins vs Gnomes",
    CardSet.BRM: "Blackrock Mountain",
    CardSet.TGT: "The Grand Tournament",
    CardSet.CREDITS: "Credits",
    CardSet.HERO_SKINS: "Hero Skins",
    CardSet.TB: "Tavern Brawl",
    CardSet.LOE: "League of Explorers",
    CardSet.OG: "Whispers of the Old Gods",
    CardSet.KARA: "One Night in Karazhan",
    CardSet.GANGS: "Mean Streets of Gadgetzan",
    CardSet.UNGORO: "Journey to Un'Goro",
    CardSet.ICECROWN: "Knights of the Frozen Throne",
    CardSet.LOOTAPALOOZA: "Kobolds and Catacombs",
    CardSet.GILNEAS: "The Witchwood",
    CardSet.BOOMSDAY: "The Boomsday Project",
    CardSet.TROLL: "Rastakhan's Rumble",
    CardSet.DALARAN: "Rise of Shadows",
    CardSet.ULDUM: "Saviors of Uldum",
    CardSet.DRAGONS: "Descent of Dragons",
    CardSet.YEAR_OF_THE_DRAGON: "Galakrond's Awakening",
    CardSet.BLACK_TEMPLE: "Ashes of Outland",
    CardSet.WILD_EVENT: "Wild Event",
    CardSet.DEMON_HUNTER_INITIATE: "Demon Hunter Initiate",
    CardSet.SCHOLOMANCE: "Scholomance Academy",
    CardSet.DARKMOON_FAIRE: "Darkmoon Faire",
    CardSet.THE_BARRENS: "The Barrens",
    CardSet.WAILING_CAVERNS: "Wailing Caverns",
    CardSet.LEGACY: "Legacy",
    CardSet.CORE: "Core",
    CardSet.VANILLA: "Vanilla",
    CardSet.STORMWIND: "United in Stormwind",
    CardSet.ALTERAC_VALLEY: "Fractured in Alterac Valley",
    CardSet.THE_SUNKEN_CITY: "Voyage to the Sunken City",
    CardSet.REVENDRETH: "Murder at Castle Nathria",
    CardSet.RETURN_OF_THE_LICH_KING: "March of the Lich King",
    CardSet.PATH_OF_ARTHAS: "Path of Arthas",
    CardSet.BATTLE_OF_THE_BANDS: "Festival of Legends",
    CardSet.TITANS: "TITANS",
    CardSet.WONDERS: "Caverns of Time",
    CardSet.WILD_WEST: "Showdown in the Badlands",
    CardSet.WHIZBANGS_WORKSHOP: "Whizbang's Workshop",
    CardSet.EVENT: "Event",
CardSet.PLACEHOLDER_202204: "PLACEHOLDER_202204",
}
